spring.datasource.url=${PROFILE_DB_URL}
spring.datasource.username=${PROFILE_DB_USERNAME}
spring.datasource.password=${PROFILE_DB_PASSWORD}
profile.security.jwk-set-uri=${AUTH_JWKS_URI}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
management.endpoint.health.show-details=never
