CREATE TABLE user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    target_weekly_hours VARCHAR(32),
    commute_range INTEGER,
    postcode VARCHAR(16),
    region VARCHAR(100),
    admin_district VARCHAR(100),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    CONSTRAINT uk_user_profile_user_id UNIQUE (user_id),
    CONSTRAINT ck_user_profile_target_weekly_hours CHECK (
        target_weekly_hours IS NULL OR target_weekly_hours IN (
            'FLEXIBLE', 'FULL_TIME', 'PART_TIME_16_30', 'PART_TIME_UNDER_16'
        )
    ),
    CONSTRAINT ck_user_profile_commute_range CHECK (
        commute_range IS NULL OR commute_range BETWEEN 0 AND 500
    ),
    CONSTRAINT ck_user_profile_latitude CHECK (
        latitude IS NULL OR latitude BETWEEN -90 AND 90
    ),
    CONSTRAINT ck_user_profile_longitude CHECK (
        longitude IS NULL OR longitude BETWEEN -180 AND 180
    )
);

CREATE TABLE user_profile_skills (
    user_profile_id BIGINT NOT NULL,
    skill VARCHAR(100) NOT NULL,
    CONSTRAINT fk_profile_skills_profile FOREIGN KEY (user_profile_id)
        REFERENCES user_profile (id) ON DELETE CASCADE
);

CREATE TABLE user_profile_target_roles (
    user_profile_id BIGINT NOT NULL,
    target_role VARCHAR(100) NOT NULL,
    CONSTRAINT fk_profile_target_roles_profile FOREIGN KEY (user_profile_id)
        REFERENCES user_profile (id) ON DELETE CASCADE
);

CREATE TABLE qualification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    qualification_name VARCHAR(200) NOT NULL,
    issuing_body VARCHAR(200) NOT NULL,
    status VARCHAR(32) NOT NULL,
    grade VARCHAR(100),
    date_achieved VARCHAR(30),
    expected_completion VARCHAR(30),
    CONSTRAINT ck_qualification_status CHECK (status IN ('COMPLETED', 'IN_PROGRESS')),
    CONSTRAINT fk_qualification_profile FOREIGN KEY (user_profile_id)
        REFERENCES user_profile (id) ON DELETE CASCADE
);

CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    job_title VARCHAR(200) NOT NULL,
    employer VARCHAR(200) NOT NULL,
    status VARCHAR(32) NOT NULL,
    start_date VARCHAR(30) NOT NULL,
    end_date VARCHAR(30),
    key_responsibilities VARCHAR(2000),
    CONSTRAINT ck_role_status CHECK (status IN ('CURRENT', 'PREVIOUS_ROLE')),
    CONSTRAINT fk_role_profile FOREIGN KEY (user_profile_id)
        REFERENCES user_profile (id) ON DELETE CASCADE
);
