ALTER TABLE user_profile
    ADD COLUMN profile_revision BIGINT NOT NULL DEFAULT 1;

ALTER TABLE user_profile
    ADD COLUMN revision_id VARCHAR(36);

ALTER TABLE user_profile
    ADD COLUMN content_digest VARCHAR(64);

ALTER TABLE user_profile
    ADD COLUMN entity_version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE user_profile
    ADD CONSTRAINT ck_user_profile_revision CHECK (profile_revision >= 1);

CREATE TABLE evidence_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id VARCHAR(36) NOT NULL,
    user_profile_id BIGINT NOT NULL,
    category VARCHAR(40) NOT NULL,
    visibility VARCHAR(16) NOT NULL,
    lifecycle VARCHAR(16) NOT NULL,
    superseded_by_entry_id VARCHAR(36),
    migration_key VARCHAR(160),
    source_hash VARCHAR(64),
    review_required BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_evidence_entry_public_id UNIQUE (entry_id),
    CONSTRAINT uk_evidence_entry_migration UNIQUE (user_profile_id, migration_key),
    CONSTRAINT fk_evidence_entry_profile FOREIGN KEY (user_profile_id)
        REFERENCES user_profile (id) ON DELETE CASCADE,
    CONSTRAINT ck_evidence_entry_category CHECK (category IN (
        'EMPLOYMENT', 'EDUCATION', 'QUALIFICATION_TRAINING', 'PROJECT',
        'VOLUNTEERING', 'FREELANCE', 'ACHIEVEMENT', 'CAREER_BREAK', 'OTHER'
    )),
    CONSTRAINT ck_evidence_entry_visibility CHECK (visibility IN ('VISIBLE', 'HIDDEN')),
    CONSTRAINT ck_evidence_entry_lifecycle CHECK (lifecycle IN ('ACTIVE', 'ARCHIVED', 'SUPERSEDED')),
    CONSTRAINT ck_evidence_entry_source_hash CHECK (
        source_hash IS NULL OR LENGTH(source_hash) = 64
    )
);

CREATE TABLE evidence_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id VARCHAR(36) NOT NULL,
    evidence_entry_id BIGINT NOT NULL,
    revision_number INTEGER NOT NULL,
    confirmation_state VARCHAR(24) NOT NULL,
    content_digest VARCHAR(64) NOT NULL,
    heading VARCHAR(200) NOT NULL,
    organisation_context VARCHAR(200),
    role_title VARCHAR(200),
    programme_or_subject VARCHAR(200),
    institution VARCHAR(200),
    qualification_title VARCHAR(200),
    issuer VARCHAR(200),
    result_or_status VARCHAR(100),
    project_role VARCHAR(200),
    description VARCHAR(4000),
    responsibilities VARCHAR(4000),
    achievements VARCHAR(4000),
    career_break_reason VARCHAR(1000),
    private_credential_identifier VARCHAR(500),
    ongoing BOOLEAN NOT NULL DEFAULT FALSE,
    start_date_precision VARCHAR(8),
    start_date_year INTEGER,
    start_date_month INTEGER,
    start_date_day INTEGER,
    end_date_precision VARCHAR(8),
    end_date_year INTEGER,
    end_date_month INTEGER,
    end_date_day INTEGER,
    issue_date_precision VARCHAR(8),
    issue_date_year INTEGER,
    issue_date_month INTEGER,
    issue_date_day INTEGER,
    expiry_date_precision VARCHAR(8),
    expiry_date_year INTEGER,
    expiry_date_month INTEGER,
    expiry_date_day INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by VARCHAR(32) NOT NULL,
    CONSTRAINT uk_evidence_revision_public_id UNIQUE (revision_id),
    CONSTRAINT uk_evidence_revision_number UNIQUE (evidence_entry_id, revision_number),
    CONSTRAINT fk_evidence_revision_entry FOREIGN KEY (evidence_entry_id)
        REFERENCES evidence_entry (id) ON DELETE CASCADE,
    CONSTRAINT ck_evidence_revision_number CHECK (revision_number >= 1),
    CONSTRAINT ck_evidence_revision_confirmation CHECK (
        confirmation_state IN ('DRAFT', 'USER_CONFIRMED')
    ),
    CONSTRAINT ck_evidence_revision_digest CHECK (LENGTH(content_digest) = 64),
    CONSTRAINT ck_evidence_revision_created_by CHECK (
        created_by IN ('USER', 'LEGACY_MIGRATION', 'SYSTEM')
    ),
    CONSTRAINT ck_evidence_revision_start_precision CHECK (
        start_date_precision IS NULL OR start_date_precision IN ('YEAR', 'MONTH', 'DAY')
    ),
    CONSTRAINT ck_evidence_revision_end_precision CHECK (
        end_date_precision IS NULL OR end_date_precision IN ('YEAR', 'MONTH', 'DAY')
    ),
    CONSTRAINT ck_evidence_revision_issue_precision CHECK (
        issue_date_precision IS NULL OR issue_date_precision IN ('YEAR', 'MONTH', 'DAY')
    ),
    CONSTRAINT ck_evidence_revision_expiry_precision CHECK (
        expiry_date_precision IS NULL OR expiry_date_precision IN ('YEAR', 'MONTH', 'DAY')
    )
);

CREATE TABLE evidence_revision_skill (
    evidence_revision_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    skill VARCHAR(100) NOT NULL,
    PRIMARY KEY (evidence_revision_id, position),
    CONSTRAINT fk_evidence_skill_revision FOREIGN KEY (evidence_revision_id)
        REFERENCES evidence_revision (id) ON DELETE CASCADE
);

CREATE TABLE evidence_supporting_link (
    evidence_revision_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    link_url VARCHAR(2048) NOT NULL,
    PRIMARY KEY (evidence_revision_id, position),
    CONSTRAINT fk_evidence_link_revision FOREIGN KEY (evidence_revision_id)
        REFERENCES evidence_revision (id) ON DELETE CASCADE
);

CREATE TABLE evidence_fact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fact_id VARCHAR(36) NOT NULL,
    evidence_revision_id BIGINT NOT NULL,
    fact_type VARCHAR(64) NOT NULL,
    fact_value VARCHAR(2000) NOT NULL,
    numeric_claim BOOLEAN NOT NULL DEFAULT FALSE,
    position INTEGER NOT NULL,
    CONSTRAINT uk_evidence_fact_public_id UNIQUE (fact_id),
    CONSTRAINT uk_evidence_fact_position UNIQUE (evidence_revision_id, position),
    CONSTRAINT fk_evidence_fact_revision FOREIGN KEY (evidence_revision_id)
        REFERENCES evidence_revision (id) ON DELETE CASCADE
);

CREATE INDEX idx_evidence_entry_owner ON evidence_entry (user_profile_id);
CREATE INDEX idx_evidence_entry_owner_state
    ON evidence_entry (user_profile_id, lifecycle, visibility);
CREATE INDEX idx_evidence_revision_entry ON evidence_revision (evidence_entry_id);
CREATE INDEX idx_evidence_fact_revision ON evidence_fact (evidence_revision_id);
