CREATE TABLE evidence_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id VARCHAR(36) NOT NULL,
    user_profile_id BIGINT NOT NULL,
    purpose VARCHAR(24) NOT NULL,
    profile_revision_id VARCHAR(36) NOT NULL,
    profile_content_digest VARCHAR(64) NOT NULL,
    snapshot_digest VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_evidence_snapshot_public_id UNIQUE (snapshot_id),
    CONSTRAINT fk_evidence_snapshot_profile FOREIGN KEY (user_profile_id)
        REFERENCES user_profile (id) ON DELETE CASCADE,
    CONSTRAINT ck_evidence_snapshot_purpose CHECK (purpose IN ('CV', 'COVER_LETTER')),
    CONSTRAINT ck_evidence_snapshot_profile_digest CHECK (LENGTH(profile_content_digest) = 64),
    CONSTRAINT ck_evidence_snapshot_digest CHECK (LENGTH(snapshot_digest) = 64)
);

CREATE TABLE evidence_snapshot_section (
    evidence_snapshot_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    category VARCHAR(40) NOT NULL,
    PRIMARY KEY (evidence_snapshot_id, position),
    CONSTRAINT fk_evidence_snapshot_section_snapshot FOREIGN KEY (evidence_snapshot_id)
        REFERENCES evidence_snapshot (id) ON DELETE CASCADE,
    CONSTRAINT ck_evidence_snapshot_section_category CHECK (category IN (
        'EMPLOYMENT', 'EDUCATION', 'QUALIFICATION_TRAINING', 'PROJECT',
        'VOLUNTEERING', 'FREELANCE', 'ACHIEVEMENT', 'CAREER_BREAK', 'OTHER'
    ))
);

CREATE TABLE evidence_snapshot_selection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evidence_snapshot_id BIGINT NOT NULL,
    entry_id VARCHAR(36) NOT NULL,
    revision_id VARCHAR(36) NOT NULL,
    revision_number INTEGER NOT NULL,
    category VARCHAR(40) NOT NULL,
    content_digest VARCHAR(64) NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT uk_snapshot_selection_position UNIQUE (evidence_snapshot_id, position),
    CONSTRAINT uk_snapshot_selection_entry UNIQUE (evidence_snapshot_id, entry_id),
    CONSTRAINT fk_snapshot_selection_snapshot FOREIGN KEY (evidence_snapshot_id)
        REFERENCES evidence_snapshot (id) ON DELETE CASCADE,
    CONSTRAINT ck_snapshot_selection_revision CHECK (revision_number >= 1),
    CONSTRAINT ck_snapshot_selection_digest CHECK (LENGTH(content_digest) = 64),
    CONSTRAINT ck_snapshot_selection_category CHECK (category IN (
        'EMPLOYMENT', 'EDUCATION', 'QUALIFICATION_TRAINING', 'PROJECT',
        'VOLUNTEERING', 'FREELANCE', 'ACHIEVEMENT', 'CAREER_BREAK', 'OTHER'
    ))
);

CREATE TABLE evidence_snapshot_fact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_selection_id BIGINT NOT NULL,
    fact_id VARCHAR(36) NOT NULL,
    fact_type VARCHAR(64) NOT NULL,
    fact_value VARCHAR(2000) NOT NULL,
    numeric_claim BOOLEAN NOT NULL DEFAULT FALSE,
    position INTEGER NOT NULL,
    CONSTRAINT uk_snapshot_fact_position UNIQUE (snapshot_selection_id, position),
    CONSTRAINT uk_snapshot_fact_id UNIQUE (snapshot_selection_id, fact_id),
    CONSTRAINT fk_snapshot_fact_selection FOREIGN KEY (snapshot_selection_id)
        REFERENCES evidence_snapshot_selection (id) ON DELETE CASCADE
);

CREATE INDEX idx_evidence_snapshot_owner_created
    ON evidence_snapshot (user_profile_id, created_at);
CREATE INDEX idx_snapshot_selection_snapshot
    ON evidence_snapshot_selection (evidence_snapshot_id);
CREATE INDEX idx_snapshot_fact_selection
    ON evidence_snapshot_fact (snapshot_selection_id);
