CREATE TABLE profile_professional_contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_profile_id BIGINT NOT NULL,
    phone VARCHAR(40),
    CONSTRAINT uk_professional_contact_profile UNIQUE (user_profile_id),
    CONSTRAINT fk_professional_contact_profile FOREIGN KEY (user_profile_id)
        REFERENCES user_profile (id) ON DELETE CASCADE,
    CONSTRAINT ck_professional_contact_phone_length CHECK (
        phone IS NULL OR CHAR_LENGTH(phone) BETWEEN 1 AND 40
    )
);

CREATE TABLE profile_professional_link (
    professional_contact_id BIGINT NOT NULL,
    position INTEGER NOT NULL,
    label VARCHAR(40) NOT NULL,
    link_url VARCHAR(512) NOT NULL,
    PRIMARY KEY (professional_contact_id, position),
    CONSTRAINT fk_professional_link_contact FOREIGN KEY (professional_contact_id)
        REFERENCES profile_professional_contact (id) ON DELETE CASCADE,
    CONSTRAINT ck_professional_link_label CHECK (
        CHAR_LENGTH(TRIM(label)) BETWEEN 1 AND 40
    ),
    CONSTRAINT ck_professional_link_url CHECK (
        CHAR_LENGTH(link_url) BETWEEN 9 AND 512
        AND link_url LIKE 'https://%'
    )
);
